name             'aem-devstax'
maintainer       'Juan Ayala'
maintainer_email 'juan.ayala.tech@gmail.com'
license          'All rights reserved'
description      'Wrapper cookbook for aem-devstax'
version          '1.0.0'
